# Generated by Django 3.2.7 on 2021-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='vk_image'),
        ),
    ]
